// const mockUser = {
//   login: 'abdullahmohamed74',
//   id: 128362734,
//   node_id: 'U_kgDOB6ao7g',
//   avatar_url: 'https://avatars.githubusercontent.com/u/128362734?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/abdullahmohamed74',
//   html_url: 'https://github.com/abdullahmohamed74',
//   followers_url: 'https://api.github.com/users/abdullahmohamed74/followers',
//   following_url:
//     'https://api.github.com/users/abdullahmohamed74/following{/other_user}',
//   gists_url: 'https://api.github.com/users/abdullahmohamed74/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/abdullahmohamed74/starred{/owner}{/repo}',
//   subscriptions_url:
//     'https://api.github.com/users/abdullahmohamed74/subscriptions',
//   organizations_url: 'https://api.github.com/users/abdullahmohamed74/orgs',
//   repos_url: 'https://api.github.com/users/abdullahmohamed74/repos',
//   events_url: 'https://api.github.com/users/abdullahmohamed74/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/abdullahmohamed74/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'Abdullah Mohamed ',
//   company: null,
//   blog: '',
//   location: null,
//   email: null,
//   hireable: null,
//   bio: 'I am a junior front end developer',
//   twitter_username: null,
//   public_repos: 25,
//   public_gists: 0,
//   followers: 0,
//   following: 0,
//   created_at: '2023-03-20T08:43:52Z',
//   updated_at: '2023-06-11T07:36:41Z',
// };

const user = {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};

export default user;
